
/*                                                    Default connection          */

CREATE TABLE data (
    id NUMBER PRIMARY KEY,         -- Unique identifier for each record
    name VARCHAR2(50),             -- Name field, up to 50 characters
    email VARCHAR2(100) UNIQUE,    -- Email field, must be unique
    created_at DATE DEFAULT SYSDATE -- Date field with a default value of the current date
);
INSERT INTO data (id, name, email) 
VALUES (1, 'Alice Johnson', 'alice.johnson@example.com');

INSERT INTO data (id, name, email) 
VALUES (2, 'Bob Smith', 'bob.smith@example.com');

INSERT INTO data (id, name, email) 
VALUES (3, 'Charlie Brown', 'charlie.brown@example.com');

SELECT * FROM data;
show pdbs;


-- Create the user
CREATE USER C##user_haroon IDENTIFIED BY haroon112233;

-- Grant the DB Developer role (adjust the role to an existing one in your database)
GRANT DB_DEVELOPER_ROLE TO C##user_haroon;


SELECT ROLE,ROLE_ID
FROM DBA_ROLES
WHERE ROLE = 'DB_DEVELOPER_ROLE';

SELECT * FROM DBA_ROLES ;

/*======================================================================================================================================================================
*/

DROP TABLE TEST_TABLE;

/* allocating memory */
ALTER USER C##USER_HAROON QUOTA 5G ON USERS;

/* GRANTING PERMISSION */
GRANT CREATE TABLE TO C##USER_HAROON;

 /* CREATING TABLE */
CREATE TABLE TEST_TABLE (
    ID NUMBER,
    NAME VARCHAR2(50)
);

SELECT TABLESPACE_NAME, 
       BYTES/1024/1024 AS FREE_SPACE_MB
FROM USER_FREE_SPACE;

SELECT TABLESPACE_NAME, 
       BYTES/1024/1024 AS FREE_SPACE_MB
FROM ALL_FREE_SPACE;

GRANT SELECT_CATALOG_ROLE TO C##USER_HAROON;

SELECT TABLESPACE_NAME, 
       BYTES/1024/1024 AS FREE_SPACE_MB
FROM DBA_FREE_SPACE
WHERE TABLESPACE_NAME = 'USERS';

/* accesing data files */
SELECT FILE_NAME 
FROM DBA_DATA_FILES;

/* RESIZING */
ALTER DATABASE DATAFILE 'C:\APP\USER\PRODUCT\23AI\ORADATA\FREE\USERS01.DBF' RESIZE 5G;


/* CHECKING STORAGE OF ALL USERS */
SELECT TABLESPACE_NAME, 
       BYTES/1024/1024 AS FREE_SPACE_MB
FROM USER_FREE_SPACE;


/* INSERTING */
INSERT INTO TEST_TABLE (ID, NAME) VALUES (1, 'Haroon');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (2, 'Ali');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (3, 'Abbas');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (4, 'Raimal');
SELECT * FROM TEST_TABLE;
TRUNCATE TABLE TEST_TABLE;

/* CHEKCING MEMORY USED BY TABLE */
SELECT SEGMENT_NAME, 
       BYTES/1024 AS SIZE_KB, 
       BYTES/1024/1024 AS SIZE_MB
FROM USER_SEGMENTS
WHERE SEGMENT_NAME = 'TEST_TABLE';

/* CHECKING TOTAL MEMORY OF USER */ 
SELECT TABLESPACE_NAME, 
       BYTES/1024/1024 AS USED_MB, 
       MAX_BYTES/1024/1024 AS MAX_MB
FROM DBA_TS_QUOTAS
WHERE USERNAME = 'C##USER_HAROON';


/* checking memory of datafile */
SELECT FILE_NAME, BYTES/1024/1024 AS SIZE_MB
FROM DBA_DATA_FILES
WHERE FILE_NAME = 'C:\APP\USER\PRODUCT\23AI\ORADATA\FREE\USERS01.DBF';

/* checking memory of user  and USERS */
SELECT USERNAME, TABLESPACE_NAME, MAX_BYTES/1024/1024 AS MAX_SIZE_MB
FROM DBA_TS_QUOTAS
WHERE USERNAME = 'C##USER_HAROON' AND TABLESPACE_NAME = 'USERS';

 /* altering and adding more memory */
ALTER USER C##USER_HAROON QUOTA 1G ON USERS;



SELECT username 
FROM dba_users 
WHERE username = 'C##USER_HAROON';

SELECT * 
FROM dba_role_privs 
WHERE grantee = 'C##USER_HAROON';

CREATE TABLE students (
    student_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100),
    age          NUMBER,
    email        VARCHAR2(100),
    enrolled_on  DATE DEFAULT SYSDATE
);

INSERT INTO students (name, age, email) 
VALUES ('Haroon Khan', 21, 'haroon@example.com');

SELECT * FROM students;